language: java

author: Guido Barbaglia "guido.barbaglia@gmail.com"

addons:
  postgresql: "9.1"

before_script:
  - psql -c 'create database travis_test;' -U postgres
  - psql -c 'CREATE TABLE Area(AreaCode TEXT, AreaNameE TEXT)' -U postgres -d travis_test
  - psql -c 'INSERT INTO Area VALUES('2', 'Afghanistan')' -U postgres -d travis_test